name: "BoltAI"
description: "The best AI app for Mac. Instantly switch between 300+ AI models, from a single native app."
url: "https://boltai.com"
docs: "https://help.boltai.com/articles/2327851-how-to-use-openrouter-in-boltai"
tags:
  - chat
date_added: "2026-01-15"
