name: "AiAssistWorks"
description: "AI for Google Sheets™, Slides™ & Docs™. Fill, clean, and categorize 100k+ rows with simple text commands—no complex formulas needed. Create charts, pivot tables, and write content using 100+ AI models."
url: "https://www.aiassistworks.com/"
docs: "https://support.aiassistworks.com/kb/article/8/setting-up-openrouter-api-key"
tags:
  - productivity
date_added: "2026-01-15"
