#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const APPS_DIR = path.join(__dirname, '..', 'apps');
const README_PATH = path.join(__dirname, '..', 'README.md');
const APPS_JSON_PATH = path.join(__dirname, '..', 'apps.json');

function loadApps() {
  const apps = [];

  if (!fs.existsSync(APPS_DIR)) {
    return apps;
  }

  const dirs = fs.readdirSync(APPS_DIR, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

  for (const dir of dirs) {
    const yamlPath = path.join(APPS_DIR, dir, 'app.yaml');
    const logoPath = path.join(APPS_DIR, dir, 'logo.png');

    if (!fs.existsSync(yamlPath)) {
      console.warn(`Warning: No app.yaml found in ${dir}`);
      continue;
    }

    try {
      const content = fs.readFileSync(yamlPath, 'utf8');
      const app = yaml.load(content);
      app._slug = dir;
      app._hasLogo = fs.existsSync(logoPath);
      apps.push(app);
    } catch (err) {
      console.error(`Error loading ${yamlPath}: ${err.message}`);
    }
  }

  return apps;
}

function generateAppCard(app) {
  const logoUrl = app._hasLogo
    ? `./apps/${app._slug}/logo.png`
    : 'https://via.placeholder.com/64?text=App';

  const openSourceBadge = app.open_source
    ? ` [![Open Source](https://img.shields.io/badge/Open%20Source-green)](${app.open_source})`
    : '';

  const tags = app.tags.map(tag => `\`${tag}\``).join(' ');

  return `### [${app.name}](${app.url})

<img src="${logoUrl}" alt="${app.name} logo" width="64" height="64">

${app.description}

${tags}${openSourceBadge}

[Documentation](${app.docs})

---`;
}

function generateAnchor(name) {
  // GitHub-style anchor generation: lowercase, replace spaces with hyphens, remove special chars
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '');
}

function generateReadme(apps) {
  const sortedApps = [...apps].sort((a, b) =>
    a.name.toLowerCase().localeCompare(b.name.toLowerCase())
  );

  // Generate table of contents
  const toc = sortedApps.map(app => {
    const anchor = generateAnchor(app.name);
    return `- [${app.name}](#${anchor})`;
  }).join('\n');

  const appCards = sortedApps.map(generateAppCard).join('\n\n');

  return `# OpenRouter App Directory

A curated list of apps and tools that work with [OpenRouter](https://openrouter.ai) - the unified API for hundreds of AI models.

## What is OpenRouter?

[OpenRouter](https://openrouter.ai) provides a single API to access models from Anthropic, OpenAI, Google, and dozens of other providers.

**Why use OpenRouter:**
- Access hundreds of models from major AI providers through one API
- Automatic failover and load balancing across providers
- No vendor lock-in

## Get Your API Key

1. Create an account at [openrouter.ai](https://openrouter.ai)
2. Add credits and generate an API key at [openrouter.ai/settings/keys](https://openrouter.ai/settings/keys)
3. Use your key with any app below or in your own projects

**Developers:** Integrate OpenRouter using the [OpenRouter SDK](https://openrouter.ai/sdk) (TypeScript, Python, Go, Java). [View documentation →](https://openrouter.ai/docs/quickstart)

<!-- DO NOT EDIT THIS FILE DIRECTLY -->
<!-- This file is auto-generated. See CONTRIBUTING.md for how to add your app. -->

## Table of Contents

${toc}

## Apps

${appCards}

## Add Your App

Want to add your app to this list? See [CONTRIBUTING.md](CONTRIBUTING.md) for instructions.

---

Powered by [OpenRouter](https://openrouter.ai)
`;
}

function main() {
  console.log('Loading apps...');
  const apps = loadApps();
  console.log(`Found ${apps.length} app(s)`);

  console.log('Generating README...');
  const readme = generateReadme(apps);

  fs.writeFileSync(README_PATH, readme);
  console.log(`README.md generated with ${apps.length} app(s)`);

  // Generate apps.json for openrouter.ai/awesome consumption
  const appsJson = apps.map(app => ({
    slug: app._slug,
    name: app.name,
    description: app.description,
    url: app.url,
    docs: app.docs,
    tags: app.tags,
    openSource: app.open_source || null,
    dateAdded: app.date_added,
  }));
  fs.writeFileSync(APPS_JSON_PATH, JSON.stringify(appsJson, null, 2));
  console.log('apps.json generated');
}

main();
