name: "Stirrup"
description: "A lightweight framework for building agents. Bring your own OpenRouter key and use `ChatCompletionsClient` to build your own agents with any model."
url: "https://github.com/ArtificialAnalysis/Stirrup"
docs: "https://stirrup.artificialanalysis.ai/"
tags:
  - productivity
date_added: "2026-01-15"
